version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      DATABASE_URL: "postgresql+asyncpg://user:pwd123@db/tasks"
    ports:
      - "8000:8000"

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: dramatiq app.tasks --processes 1 --threads 1
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      DATABASE_URL: "postgresql+asyncpg://user:pwd123@db/tasks"
    expose:
      - "9191"

  redis:
    restart: unless-stopped
    image: redis:latest
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data
    expose:
      - "6379"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  redis_data:

